#!/usr/bin/env python3
"""
APEX DOSSIER LINKER
Automatically links newly organized forensic evidence to the TARGET_DOSSIER.md.
"""

import os
import json
from pathlib import Path
from datetime import datetime

# Configuration
DOSSIER_PATH = Path("/Users/macarena1/dev/projects/apex-fs-commander/legal_documents/intel/TARGET_DOSSIER.md")
DROPBOX_STATE = Path("/Users/macarena1/Library/CloudStorage/Dropbox-Kahalainspector/Kahala Home Inspectors/Case_1FDV-23-0001009_ORGANIZED/dropbox_organization_state.json")
ORGANIZED_DIR = Path("/Users/macarena1/Library/CloudStorage/Dropbox-Kahalainspector/Kahala Home Inspectors/Case_1FDV-23-0001009_ORGANIZED")

def run_dossier_linker():
    print("🧠 Starting APEX Dossier Linker...")
    
    if not DOSSIER_PATH.exists() or not DROPBOX_STATE.exists():
        print("  ⚠️ Dossier or State file missing.")
        return

    # Load state
    state = json.loads(DROPBOX_STATE.read_text())
    processed_files = state.get("processed_files", {})
    
    # Read current dossier
    dossier_content = DOSSIER_PATH.read_text()
    
    # Identify high-impact categories
    impact_categories = {
        "01_COURT_FILINGS/01b_Casey_Motions": "📝 Casey Motion",
        "01_COURT_FILINGS/01d_Court_Orders": "📜 Court Order",
        "02_EVIDENCE/02c_Medical_Records": "🏥 Medical Evidence",
        "11_TECH_TOOLS/11c_Apex_Code": "💻 Apex Intel"
    }

    new_links = []
    
    # Sort files by processed_at to get newest first
    sorted_files = sorted(
        [(k, v) for k, v in processed_files.items() if v.get("status") == "success"],
        key=lambda x: x[1].get("processed_at", 0),
        reverse=True
    )

    for src_path, info in sorted_files:
        category = info.get("category")
        if category in impact_categories:
            file_name = Path(src_path).name
            rel_path = info.get("destination")
            
            # Check if already in dossier
            if file_name in dossier_content:
                continue
            
            label = impact_categories[category]
            link_line = f"- [{label}: {file_name}]({rel_path})"
            new_links.append(link_line)

    if not new_links:
        print("  ✅ No new impact files to link.")
        return

    # Append new links to the end of the dossier or before the signature
    print(f"  🔗 Linking {len(new_links)} new evidence items to dossier...")
    
    header = f"\n### AUTO-LINKED EVIDENCE ({datetime.now().strftime('%Y-%m-%d')})\n"
    new_section = header + "\n".join(new_links) + "\n"
    
    if "*Generated by Apex Nexus Coordinator.*" in dossier_content:
        updated_content = dossier_content.replace(
            "*Generated by Apex Nexus Coordinator.*",
            new_section + "\n*Generated by Apex Nexus Coordinator.*"
        )
    else:
        updated_content = dossier_content + "\n" + new_section
        
    DOSSIER_PATH.write_text(updated_content)
    print("  🎉 Dossier updated.")

if __name__ == "__main__":
    run_dossier_linker()
